### ISSUE TITLE
DogeCoin not working

### ISSUE THREAD

**Issue by selcuktatar** [ozgrozer/tweet-chart#1]
<img width="941" alt="doge" src="https://user-images.githubusercontent.com/41347478/112768838-9b160280-9026-11eb-8267-803c469ce8bb.png">
DogeCoin not working. Is normal?

**Comment by ozgrozer** [comment]
I think it should be fixed now, thanks.

![tweet-chart](https://user-images.githubusercontent.com/651938/112769848-00b8bd80-902c-11eb-839d-5c85731d8ecf.png)

**Comment by selcuktatar** [comment]
Always 🚀
